name: Environment-test

on:
  workflow_dispatch:
    inputs:
      env:
        default: 'production'

jobs:
  hoge:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: test step hoge
        if:  ${{ secrets.TEST == 'hoge' }}
        run: echo Hello hoge
      - name: test step fuga
        if:  ${{ secrets.TEST == 'fuga' }}
        run: echo Hello fuga
