name: Environment-test

on:
  workflow_dispatch:
    inputs:
      env:
        default: 'production'

jobs:
  hoge:
    runs-on: ubuntu-latest
    environment: development
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v3
      - name: test1
        if:  ${{ env.TEST == 'hoge' }}
        run: echo 'Hello1'
      - name: test2
        if:  ${{ env.TEST == 'fuga' }}
        run: echo 'Hello2'
