name: Environment-test

on:
  workflow_dispatch:
    inputs:
      env:
        default: 'production'

jobs:
  hoge:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}
    env:
      TEST: ${{ secrets.TEST }}
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello ${TEST}
